name: ja_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter     
  firebase_database: ^9.0.16
  firebase_storage: ^10.2.18
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  cupertino_icons: ^1.0.2
  form_field_validator: ^1.1.0
  google_fonts: ^3.0.1
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  flutter_meedu: ^7.0.0
  freezed: ^2.0.3+1
  cloud_firestore: ^3.1.14
  firebase_core_platform_interface: ^4.4.0
  path_provider: ^2.0.11
  data_table_2: ^2.0.0
  firebase_messaging: ^13.1.0
  #flutter_local_notifications: ^13.0.0
  awesome_notifications: ^0.7.4+1
  flutter_email_sender: ^5.2.0
  mailer: ^6.0.0
  google_sign_in: ^5.4.3
  

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.0.3
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/logo_main5.png"
  adaptive_icon_background: "assets/images/logo_main5.png"


dependency_overrides:
  image_picker_android: 0.8.4+13
  
flutter:

 
  uses-material-design: true
  
  assets:
    - assets/icon/
    - assets/images/
  #   - images/a_dot_ham.jpeg
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
